#!/bin/sh

name=`basename $0`
usage="Usage: $name [--version] [--format=png|svg|ps] codecfile"
fmt="svg"
version="1.0"

while test $# -gt 0 ; do
    optarg=`echo $1|cut -f2 -d=`
    case "${1}" in
    --format=*)			# specify output file format
	fmt=$optarg
        ;;
    --output=*)
	outfile=$optarg
	;;
    --version)			# display version information
	echo "$name $version"
	exit 0
        ;;
    -*)
        echo "${usage}" 1>&2
        exit 1
        ;;
    *)
        break
        ;;
    esac
    shift
done

codecfile=$1

if [ -z "$codecfile" ]; then
    echo "${usage}" 1>&2
    exit 0
fi

echo|codecgraph.py >/dev/null 2>&1
if [ $? -eq 127 ]; then
    echo "error: can't find codecgraph.py in PATH (package corrupt?)" >&2
    exit 1
fi

echo|dot >/dev/null 2>&1
if [ $? -eq 127 ]; then
    echo "error: dot executable not found (did you install graphviz?)" >&2
    exit 1
fi

if [ ! -r "$codecfile" ]; then
    echo "error: can't read input file $codecfile" >&2
    exit 1
fi

if [ -z "$outfile" ]; then
    outfile="`basename $codecfile`"
fi

cat $codecfile | grep -v "^[\t ]*$" | head -1 | grep ^Codec:
if [ $? -ne 0 ]; then
    echo "error: $codecfile not a codec description" 2>&1
    exit 1
fi

dotfile=`mktemp -t codecgraph.XXXXXX`
codecgraph.py $codecfile > $dotfile
echo Generating $outfile.$fmt
dot -T$fmt -o$outfile.$fmt $dotfile
rm $dotfile

